### ISSUE TITLE
Package name is prefixed in front of the existing package name

### ISSUE THREAD

**Issue by cmoulliard** [obsidian-toaster/obsidian-addon#1]
When the project is populated from the quickstart, the name defined within the UI screen is prefixed. See hereafter

Wizard package name defined : io.demo.vertx.rest
Generated package name : io.demo.vertx.rest.org.jboss.obsidian.quickstart 

![screenshot 2016-11-28 19 26 24](https://cloud.githubusercontent.com/assets/463790/20680764/b8996276-b5a0-11e6-93ed-8dbf7fcd6974.png)

**Comment by gastaldi** [comment]
Fixed
