### ISSUE TITLE
upgrade to fabric8 2.2.204 to fix arquillian related issues around namespaces/projects + security

### ISSUE THREAD

**Issue by jstrachan** [obsidian-toaster/obsidian-addon#19]
fabric8-arquillian has been updated to not by default create namespaces on the fly and not update Namespace/ProjectRequests with status updates (which typically doesn't work OOTB on OSO). For more details see: https://github.com/fabric8io/fabric8/issues/6799

So we should update the quickstarts + wizards to use the latest fabric8 version now so that system tests are more likely to work OOTB for obsidian created projects on any OpenShift cluster

**Comment by gastaldi** [comment]
It would be nice to have this listed in the Trello board, since it requires changes to the quickstarts

**Comment by jstrachan** [comment]
@gastaldi any chance you could do that please? I don't use Trello & have no clue where you mean

**Comment by gastaldi** [comment]
Sure, on it.

**Comment by gastaldi** [comment]
Actually I think the right place is https://issues.jboss.org/browse/OBST, let me check

**Comment by jstrachan** [comment]
@gastaldi thanks! I think the latest fabric8 + fmp should work now for WARs and other obsidian project kinds

**Comment by gastaldi** [comment]
Created on https://issues.jboss.org/browse/OBST-149

**Comment by gastaldi** [comment]
Closing issue as it's now in JIRA
